mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin, auth
from posts import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("posts.urls", namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from posts import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$', views.post_list, name='list'),
    url(r'^post/(?P<id>\d+)$', views.post_detail, name='post_detail'),
    url(r'^postform', views.post_form, name='post_form'),
    url(r'^post/(?P<id>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<id>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^(?P<id>[\d+]+)/like/$', views.PostLikeToggle.as_view(), name='like-toggle'),
    url(r'^api/(?P<id>[\d+]+)/like/$', views.PostLikeAPIToggle.as_view(), name='like-api-toggle'),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout'),
    url(r'^accounts/sing_up/$', views.sing_up, name='sing_up'),
    url(r'^confirm/(?P<confirmation_code>[^/]+)/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', views.confirm, name='confirm'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import models as auth_models
from django.core.urlresolvers import reverse
from django.utils import timezone

from mysite import settings

from lib import uploads, country_list


__author__ = 'Yevhenii Onoshko'

COUNTRY = list(country_list.generate_country_list())


class UserManager(auth_models.BaseUserManager):
    """
    Custom User Manager. Needed for Django auth to work with custom User model
    """
    def create_user(self, email, password, is_super=False, **kwargs):
        """
        Creates and saves User
        """
        if not email:
            raise ValueError('Users must have an email address')
        if is_super:
            user = self.model(
                email=UserManager.normalize_email(email),
            )
            user.save(using=self._db)
        else:
            user = self.model(
                email=UserManager.normalize_email(email),
                first_name = kwargs['first_name'] or None,
                last_name = kwargs['last_name'] or None,
                username=kwargs['username'] or None,
                birthday=kwargs['birthday'] or None,
                country=kwargs['country'] or None,
                city=kwargs['city'] or None,
                confirmation_code=kwargs['confirmation_code'] or None,)
            user.save(using=self._db)
        user.set_password(password)
        user.save(using=self._db)
        return user


    def create_superuser(self, email, password):
        """
        Creates and saves superuser
        """
        user = self.create_user(email=email, password=password, is_super=True )
        user.is_superuser = True
        user.is_staff = True
        user.is_active = True
        user.save(using=self._db)
        return user


class User(auth_models.PermissionsMixin, auth_models.AbstractBaseUser):
    """
    Custom User Model. Use email as username.
    Needed to override default Django User which use username as username :)

    """
    registered = models.DateField(auto_now_add=True)
    email = models.EmailField(max_length=128, unique=True)
    username = models.CharField(max_length=128, blank=True, null=True)
    first_name = models.CharField(max_length=128, blank=True)
    last_name = models.CharField(max_length=128, blank=True)
    birthday = models.DateField(blank=True, null=True)
    country = models.CharField(max_length=128, choices=COUNTRY)
    city = models.CharField(max_length=128)
    confirmation_code = models.CharField(max_length=128, blank=True, null=True)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    objects = UserManager()

    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def get_short_name(self):
        return self.get_full_name()


    def __str__(self):
        return self.get_full_name()


    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        super(User, self).save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields
        )

    def has_module_perms(self, app_label):
        return True

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="post_likes")
    title = models.CharField("Title", max_length=128, null=True)
    description = models.TextField("Description", null=True)
    image = models.ImageField("Image", upload_to=uploads.get_document_upload_path, null=True)

    def get_absolute_url(self):
        return reverse("posts:post_detail", kwargs={'id': self.id})

    def get_like_url(self):
        return reverse("posts:like-toggle", kwargs={"id": self.id})

    def get_api_like_url(self):
        return reverse("posts:like-api-toggle", kwargs={"id": self.id})
    
    class Meta:
        ordering = ["-id",]

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    author = models.ForeignKey(User, related_name='users')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

posts/views.py
import random
import string
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import EmailMessage
from django.utils import timezone
from django.db.models import Q
from django.views.generic import RedirectView
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from datetime import datetime, timedelta
from posts import forms, models

try:
    from urllib.parse import urlparse
except ImportError:
     from urlparse import urlparse


@login_required(login_url="accounts/login/")
def post_form(request):
    """
    Posts

    :param request: django.http.request.HttpRequest
    :return: django.http.response.HttpResponse or django.http.response.HttpResponseRedirect
    """
    context = models.Post.objects.all()
    form = forms.PostForm()
    if request.method == 'POST':
        form = forms.PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = models.Post.objects.create(user=request.user,
                                              title=form.cleaned_data['title'],
                                              description=form.cleaned_data['description'],
                                              image=request.FILES['image'])
            post.save()
            return redirect('/')
    return render(request, 'post_form.html', context={'form': form,
                                             'context': context})


@login_required(login_url="accounts/login/")
def post_list(request):
    today = timezone.now().date()
    queryset_list = models.Post.objects.all()
    
    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
                Q(title__icontains=query)|
                Q(description__icontains=query)|
                Q(user__country__icontains=query) |
                Q(user__city__icontains=query)
                ).distinct()
    paginator = Paginator(queryset_list, 8) # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    
    context = {
        "object_list": queryset, 
        "title": "List",
        "page_request_var": page_request_var,
        "today": today,
    }
    return render(request, "post_list.html", context)


@login_required(login_url="accounts/login/")
def comment_remove(request, id):
    comment = get_object_or_404(models.Comment, id=id)
    comment.delete()
    return redirect('post_detail', id=comment.post.id)


@login_required(login_url="accounts/login/")
def add_comment_to_post(request, id):
    post = get_object_or_404(models.Post, id=id)
    if request.method == "POST":
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            comment = models.Comment.objects.create(author=request.user,
                                                    post=post,
                                                    text=form.cleaned_data['text'])
            comment.save()
            return redirect('posts:post_detail', id=post.id)
    else:
        form = forms.CommentForm()
    return render(request, 'add_comment_to_post.html', {'form': form})


@login_required(login_url="accounts/login/")
def post_detail(request, id):
    instance = get_object_or_404(models.Post, id=id)
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    paginator = Paginator(instance.comments.all(), 3) # Show 25 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        comments = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        comments = paginator.page(paginator.num_pages)
    initial_data = {
            "content_type": instance.get_content_type,
            "object_id": instance.id
    }
    
    context = {
        "title": instance.title,
        "description": instance.description,
        "image": instance.image,
        "instance": instance,
        "comments": comments,
        "page_request_var": page_request_var,
    }
    return render(request, "post_detail.html", context)


@login_required(login_url="accounts/login/")
def post_like(request, *args, **kwargs):
    post_id = kwargs.get('post_id')
    obj = models.Post.objects.get(id=int(post_id))
    url_ = obj.get_like_url()
    user = request.user
    if user.is_authenticated():
        if user in obj.likes.all():
            obj.likes.remove(user)
        else:
            obj.likes.add(user)
    return redirect('/')


def login(request, page='login'):
    """
    Logs User in

    :param request: django.http.request.HttpRequest
    :return: django.http.response.HttpResponse or django.http.response.HttpResponseRedirect
    """
    form = forms.LoginForm()
    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            print(form.changed_data)
            user = auth.authenticate(email=form.cleaned_data['email'],
                                     password=form.cleaned_data['password'])
            if user:
                if user.is_authenticated():
                    auth.login(request, user)
                    return redirect('/')
    return render(request, 'login.html', context={'form': form})


@login_required
def logout(request):
    """
    Logs User out and redirect to Index page

    :param request: django http.request.HttpRequest
    :return: django.http.response.HttpResponseRedirect
    """
    if request.user.is_authenticated():
        auth.logout(request)
    return redirect('posts:list')


def send_email(request, user):
    msg = EmailMessage("Account confirmation",
                       "http://mysite-test-task.herokuapp.com/confirm/" + str(user.confirmation_code) + "/" + user.email,
                       to=[user.email])
    msg.send()
    return HttpResponseRedirect('/')


def send_registration_confirmation(request, user):
	send_email(request, user)


def confirm(request, confirmation_code, email):
    user = models.User.objects.get(email=email)
    try:
        if user.confirmation_code == confirmation_code:
            user.is_active = True
            user.save()
            return redirect('posts:list')
        else:
            user.delete()
            raise ValueError('Confirmation_code: {}, Email: {}'.format(confirmation_code, email))
    except:
        user.delete()
        raise ValueError('Confirmation_code: {}, Email: {}'.format(confirmation_code, email))


def sing_up(request, page='sing_up'):
    form = forms.SingUpForm()
    if request.method == 'POST':
        form = forms.SingUpForm(request.POST)
        if form.is_valid():
            print(form.changed_data)
            try:
                user = models.User.objects.get(email=form.cleaned_data['email'])
                raise ValueError('This email address already exists. Please try again')
            except:
                confirmation_code = ''.join(random.choice(string.ascii_uppercase + string.digits + string.ascii_lowercase) for x in range(33))
                user = models.User.objects.create_user(
                    email=form.cleaned_data['email'],
                    password=form.cleaned_data['password'],
                    username=form.cleaned_data['username'],
                    first_name=form.cleaned_data['first_name'],
                    last_name=form.cleaned_data['last_name'],
                    birthday=form.cleaned_data['birthday'],
                    country=form.cleaned_data['country'],
                    city=form.cleaned_data['city'],
                    confirmation_code=confirmation_code)
                send_registration_confirmation(request, user)
                return render(request, 'login.html', context={'form': form,
                                                              'message': 'Please confirm your email and then you can login'})
    return render(request, 'sing_up.html', context={'form': form})


class PostLikeToggle(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        id = self.kwargs.get("id")
        print(id)
        obj = get_object_or_404(models.Post, id=id)
        url_ = obj.get_absolute_url()
        user = self.request.user
        if user.is_authenticated():
            if user in obj.likes.all():
                obj.likes.remove(user)
            else:
                obj.likes.add(user)
        return url_


class PostLikeAPIToggle(APIView):
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, id, format=None):
        # id = self.kwargs.get("id")
        obj = get_object_or_404(models.Post, id=id)
        url_ = obj.get_absolute_url()
        user = self.request.user
        updated = False
        liked = False
        if user.is_authenticated():
            if user in obj.likes.all():
                liked = False
                obj.likes.remove(user)
            else:
                liked = True
                obj.likes.add(user)
            updated = True
        data = {
            "updated": updated,
            "liked": liked
        }
        return Response(data)

templates/add_comment_to_post.html
{% extends 'base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="ie6 ielt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="ie7 ielt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="ie8"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <title>My site</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    

</head>

<body>

    <div class="container">
        <section id="content">
            {% block content %}

            {% endblock %}
        </section>
        <!-- content -->
    </div>
    <!-- container -->

<script src="{% static 'js/base.js' %}"></script>
</body>

</html>

templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="ie6 ielt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="ie7 ielt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="ie8"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
<meta charset="utf-8">
<title>Singin</title>

<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
</head>
<body>
<div class="container">
	<section id="content">
		<form action="{% url 'posts:login'%}?next=/" method="post">
            {% csrf_token %}
			<h1>Singin Form</h1>
			{% if message %}
				<p>{{ message }}</p>
			{% endif %}
			<div class="input-group">
				{{ form.email }}
			</div>
			<div class="input-group">
				{{ form.password }}
			</div>
            {% if form.errors %}
                <div style="color: red;">{{ form.errors }}</div>
            {% endif %}
			<div>
				<input type="submit" value="Sing in" />
				<a href="{% url 'posts:sing_up'%}">Sing up</a>
			</div>
		</form><!-- form -->

		<div class="button">
		</div><!-- button -->
	</section><!-- content -->
</div><!-- container -->
</body>
</html>

templates/post_detail.html
{% extends "base.html" %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}


 {% block post_detail_link %}
  <li><a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></li>
  {% endblock %}



{% block content %}
<h3><a href="{% url 'posts:list'%}">Go To Main Page</a></h3>
<div class='col-sm-6 col-sm-offset-3'>
    {% if instance.image %}
    <img src='{{ instance.image.url }}' class='img-responsive' />
    {% endif %}
<h2>{{ title }} </h2>
<h3>{{ description }} </h3>

<!-- {% if instance.read_time|time:"i" <= "01" %} < 1 minute {% else %}{{ instance.read_time|time:"i" }} minutes {% endif %} -->


<p><a class='like-btn' data-href='{{ instance.get_api_like_url }}' data-likes='{{ instance.likes.count }}' href='{{ instance.get_like_url }}'>{{ instance.likes.count }} Like</a></p>
{% if instance.user.get_full_name %}
<p>Author: {{ instance.user.get_full_name }}</p>
{% endif %}

<p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
<hr/>
</p>
<div class='row'>
<div class='col-sm-12 '>

    <div class='post-detail-item'>
        {{ instance.content|safe }}
      </div>

    <hr/>
    <br/>

</div>
</div>
</div>
<hr>
<a class="btn btn-default" href="{% url 'posts:add_comment_to_post' id=instance.id %}">Add comment</a>
{% for comment in comments %}
    {% if user.is_authenticated and user.is_staff %}
    <div class="comment">
        <div class="date">
            {{ comment.created_date }}
            {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url 'posts:comment_remove' id=comment.id %}"><span class="glyphicon glyphicon-remove"></span></a>
            {% endif %}
        </div>
        <strong>{{ comment.author.get_full_name }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
    {% endif %}
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if comments.has_previous %}
            <a href="?{{ page_request_var }}={{ comments.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ instan.number }} of {{ comments.paginator.num_pages }}.
        </span>

        {% if comments.has_next %}
            <a href="?{{ page_request_var }}={{ comments.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

templates/post_form.html
{% extends "base.html" %}

{% block content %}
 <form action="{% url 'posts:post_form'%}?next=/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Create post</h1>
    <div class="input-group">
        {{ form.title }}
    </div>
    <div class="input-group">
        {{ form.description }}
    </div>
    <div class="input-group">
        {{ form.image }}
    </div>
    {% if form.errors %}
        <div style="color: red;">{{ form.errors }}</div>
    {% endif %}
    <button type="submit">Submit</button>
</form><!-- form -->
{% endblock%}

templates/post_list.html
{% extends "base.html" %}
{% block content %}

<h3><a href="{% url 'posts:logout'%}">Sing Out</a></h3> <h3><a href="{% url 'posts:post_form'%}">Create Post</a></h3>
<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ title }}</h1>
<form method='GET' action='' class='row'>
        <div class='col-sm-6'>
            <div class='input-group'>
                <input class='form-control' type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
                <span class='input-group-btn'>
                    <!-- <input class='btn btn-default' type='submit' value='Search' /> -->
                    <button class='btn btn-default' type='submit'>Search <i class="fa fa-search"></i></button>
                </span>
            </div>
        </div>
</form>
{% for obj in object_list %}
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
        {% if obj.image %}
         <img src='{{ obj.image.url }}' class='img-responsive' />
        {% endif %}
      <div class="caption post-detail-item">
        <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> </h3>
        <h4>{{ obj.description }}</h4>
        <p><a class='like-btn' data-href='{{ obj.get_api_like_url }}' data-likes='{{ obj.likes.count }}'  href='{{ obj.get_like_url }}'>{{ obj.likes.count }} Like</a></p>
        {% if obj.user.get_full_name %}<p>Author: {{ obj.user.get_full_name }}</p>{% endif %}
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
  </div>
<hr/>
</div>
{% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>




</div>

{% endblock content %}

templates/sing_up.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="ie6 ielt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="ie7 ielt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="ie8"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <title>Singup</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
</head>

<body>
    <div class="container">
        <section id="content">
            <form action="{% url 'posts:sing_up'%}?next=/" method="post">
                {% csrf_token %}
                <h1>Singup Form</h1>
                <div class="input-group">
                </div>
                <div class="input-group">
                    {{ form.email }}
                </div>
                <div class="input-group">
                    {{ form.password }}
                </div>
                <div class="input-group">
                    {{ form.username }}
                </div>
                <div class="input-group">
                    {{ form.first_name }}
                </div>
                <div class="input-group">
                    {{ form.last_name }}
                </div>
                <div class="input-group" name="birthday">
                    <label for="id_birthday" name="birthday">Your Birthday</label>
                </div>
                <div class="input-group" id="id_birthday">
                    {{ form.birthday }}
                </div>
                <div class="input-group">
                    <label for="id_country" name="country">Your Country</label>
                    {{ form.country }}
                </div>
                <div class="input-group">
                    {{ form.city }}
                </div>
                {% if form.errors %}
                <div style="color: red;">{{ form.errors }}</div>
                {% endif %}
                <div>
                    <input type="submit" value="Sing up" />
                    <a href="{% url 'posts:login'%}">Sing in</a>
                </div>
            </form>
            <!-- form -->

            <div class="button">
            </div>
            <!-- button -->
        </section>
        <!-- content -->
    </div>
    <!-- container -->
</body>

</html>